name: Linux Release
permissions:
  contents: write

on:
  workflow_dispatch:
  # push:

jobs:
  linux-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Deps
        run: yarn install && npm i sharp

      - name: Modify
        run: |
          # sidebar
          sed -i 's/NextChat/Aozora.Chat/' app/components/sidebar.tsx
          sed -i 's/Build your own AI assistant./May This Journey Lead Us Starward./' app/components/sidebar.tsx
          # configs
          sed -i 's/avatar.*/avatar: "2b55",/' app/store/config.ts
          sed -i 's/sendPreviewBubble.*/sendPreviewBubble: false,/' app/store/config.ts
          sed -i 's/dontShowMaskSplashScreen.*,/dontShowMaskSplashScreen: true,/' app/store/config.ts
          # title
          sed -i 's/title.*/title: "Aozora.Chat",/' app/layout.tsx
          sed -i 's/description.*/description: "May This Journey Lead Us Starward.",/' app/layout.tsx
          # emoji src
          sed -i 's#https://fastly.jsdelivr.net/npm/emoji-datasource-apple#https://cdn.staticfile.net/emoji-datasource-apple/15.0.1#' app/components/emoji.tsx

      - name: Build
        run: yarn build

      - name: Package
        run: |
          cd .next && rm -r standalone/.next/server
          mv server static standalone/.next
          mv ../public standalone
          mv standalone chatgpt-next-web
          zip -r ../chatgpt-next-web.zip chatgpt-next-web

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: chatgpt-next-web.zip
          path: chatgpt-next-web.zip

      - name: Generate release tag
        id: gen_tag
        run: |
          echo "::set-output name=release_tag::Build_v$(date +"%Y%m%d_%H%M%S")"

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: chatgpt-next-web.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ steps.gen_tag.outputs.release_tag }}
